import { afterEach, describe, expect, it, vi } from 'vitest';
import jwt from 'jsonwebtoken';

const BASE_ENV = {
    NODE_ENV: 'test',
    PORT: '3001',
    DB_HOST: 'localhost',
    DB_PORT: '5432',
    DB_NAME: 'estuarriendo_test',
    DB_USER: 'postgres',
    DB_PASSWORD: 'postgres',
    JWT_SECRET: 'this_is_a_very_strong_secret_for_testing_12345',
    JWT_EXPIRES_IN: '7d',
    ALLOWED_ORIGINS: 'http://localhost:5173,http://localhost:3000',
};

const setEnv = (overrides = {}) => {
    process.env = {
        ...BASE_ENV,
        ...overrides,
    };
};

describe('jwtUtils', () => {
    afterEach(() => {
        vi.resetModules();
    });

    it('verifies a real signed token generated by generateToken()', async () => {
        setEnv();
        const { generateToken, verifyToken } = await import('./jwtUtils.js');

        const token = generateToken('user-123');
        const decoded = verifyToken(token);

        expect(decoded.userId).toBe('user-123');
    });

    it('rejects a real signed token when payload does not include userId', async () => {
        setEnv();
        const { verifyToken } = await import('./jwtUtils.js');
        const { env } = await import('../config/env.js');

        const tokenMissingUserId = jwt.sign({ role: 'user' }, env.jwt.secret, { expiresIn: '7d' });

        expect(() => verifyToken(tokenMissingUserId)).toThrow('Token inválido');
    });
});
